using UnityEngine;

// Generated by claude code
public class LazerAnimator : MonoBehaviour
{
    [Header("Animation")]
    public Sprite[] sprites;
    public float fps = 12f;

    private LineRenderer _lr;
    private Material _mat;
    private Texture2D[] _bakedFrames;
    private float _timer;
    private int _currentFrame;

    void Start()
    {
        _lr = GetComponent<LineRenderer>();
        _mat = _lr.material;

        BakeFrames();
    }

    void BakeFrames()
    {
        if (sprites == null || sprites.Length == 0) return;

        // Find the max extents from pivot in each direction across all sprites
        float maxLeft = 0f;
        float maxRight = 0f;
        float maxDown = 0f;
        float maxUp = 0f;

        for (int i = 0; i < sprites.Length; i++)
        {
            Rect rect = sprites[i].textureRect;
            Vector2 pivot = sprites[i].pivot; // in pixels, relative to sprite rect

            float left = pivot.x;
            float right = rect.width - pivot.x;
            float down = pivot.y;
            float up = rect.height - pivot.y;

            if (left > maxLeft) maxLeft = left;
            if (right > maxRight) maxRight = right;
            if (down > maxDown) maxDown = down;
            if (up > maxUp) maxUp = up;
        }

        int maxW = Mathf.CeilToInt(maxLeft + maxRight);
        int maxH = Mathf.CeilToInt(maxDown + maxUp);

        _bakedFrames = new Texture2D[sprites.Length];

        for (int i = 0; i < sprites.Length; i++)
        {
            Rect rect = sprites[i].textureRect;
            int w = (int)rect.width;
            int h = (int)rect.height;
            Vector2 pivot = sprites[i].pivot;

            Color[] srcPixels = sprites[i].texture.GetPixels(
                (int)rect.x, (int)rect.y, w, h
            );

            _bakedFrames[i] = new Texture2D(maxW, maxH, TextureFormat.RGBA32, false);
            _bakedFrames[i].wrapMode = TextureWrapMode.Repeat;
            _bakedFrames[i].filterMode = sprites[i].texture.filterMode;

            Color[] dstPixels = new Color[maxW * maxH];

            // Align this sprite's pivot to the shared pivot point (maxLeft, maxDown)
            int offsetX = Mathf.FloorToInt(maxLeft - pivot.x);
            int offsetY = Mathf.FloorToInt(maxDown - pivot.y);

            for (int y = 0; y < h; y++)
            {
                for (int x = 0; x < w; x++)
                {
                    int dstX = x + offsetX;
                    int dstY = y + offsetY;

                    if (dstX < 0 || dstX >= maxW || dstY < 0 || dstY >= maxH)
                        continue;

                    dstPixels[dstY * maxW + dstX] = srcPixels[y * w + x];
                }
            }

            _bakedFrames[i].SetPixels(dstPixels);
            _bakedFrames[i].Apply();
        }

        ApplyFrame(0);
    }

    void Update()
    {
        if (_bakedFrames == null || _bakedFrames.Length == 0) return;

        _timer += Time.deltaTime;
        if (_timer >= 1f / fps)
        {
            _timer -= 1f / fps;
            _currentFrame = (_currentFrame + 1) % _bakedFrames.Length;
            ApplyFrame(_currentFrame);
        }
    }

    void ApplyFrame(int index)
    {
        _mat.mainTexture = _bakedFrames[index];
        _mat.mainTextureScale = Vector2.one;
        _mat.mainTextureOffset = Vector2.zero;
    }

    void OnDestroy()
    {
        if (_bakedFrames != null)
        {
            for (int i = 0; i < _bakedFrames.Length; i++)
            {
                if (_bakedFrames[i] != null)
                    Destroy(_bakedFrames[i]);
            }
        }

        if (_mat != null)
            Destroy(_mat);
    }
}